name: To do

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  schedule:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
